# Site settings
title: Wajug
email: info@wajug.be
description: > # this means to ignore newlines until "baseurl:"
  WAJUG est votre groupe d'utilisateurs local, Wallon, abordant "tout ce qui touche au développement logiciel". 
  Tout ceci dans une ambiance fun, amicale, ouverte et typiquement wallonne.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wajug.be" # the base hostname & protocol for your site
twitter_username: wajug
github_username:  wajug

# Build settings
markdown: kramdown

# Process Posts even if they are in the future
future: true

permalink: /:categories/:year/:title